### ISSUE TITLE
Interested in the project

### ISSUE THREAD

**Issue by ConsoleTVs** [Despatch/Despatch#1]
Kinda interested in what is this project. We allow modification using MIT license but not ownership. What is the main goal of this project?

If you want to build a cms, why not work with us instead of using our code?

**Comment by ashleybakernz** [comment]
We are not taking ownership of this. we were going to modify it but sadly the code is not up to laravel standards and is not capable of what we are after. We just wanted to see how it could work intergrated with some of our systems. The forks will most likely be removed over the next day as they are surplus to our needs.

**Comment by ashleybakernz** [comment]
Feel free to email me for futher questions. 

ashleybakernz@gmail.com
